// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlaey8pzBas4_4utYzKPTdhv_Wory4_Is',
    appId: '1:986993407042:web:0b2c4b47f83ee40d03e9db',
    messagingSenderId: '986993407042',
    projectId: 'spacex-57942',
    authDomain: 'spacex-57942.firebaseapp.com',
    storageBucket: 'spacex-57942.appspot.com',
    measurementId: 'G-M9K6869ZT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwqROpL4wVf79CsT85xk-XR7tqnWL2TmY',
    appId: '1:986993407042:android:ac02adacce3988e703e9db',
    messagingSenderId: '986993407042',
    projectId: 'spacex-57942',
    storageBucket: 'spacex-57942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClzMasc-ClVp3nlxe7zIn4W6fTGJETBvc',
    appId: '1:986993407042:ios:77c185a47b41c6e903e9db',
    messagingSenderId: '986993407042',
    projectId: 'spacex-57942',
    storageBucket: 'spacex-57942.appspot.com',
    iosBundleId: 'com.example.galaxyxgate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClzMasc-ClVp3nlxe7zIn4W6fTGJETBvc',
    appId: '1:986993407042:ios:77c185a47b41c6e903e9db',
    messagingSenderId: '986993407042',
    projectId: 'spacex-57942',
    storageBucket: 'spacex-57942.appspot.com',
    iosBundleId: 'com.example.galaxyxgate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlaey8pzBas4_4utYzKPTdhv_Wory4_Is',
    appId: '1:986993407042:web:6ae424f99f6a2a5f03e9db',
    messagingSenderId: '986993407042',
    projectId: 'spacex-57942',
    authDomain: 'spacex-57942.firebaseapp.com',
    storageBucket: 'spacex-57942.appspot.com',
    measurementId: 'G-GTKEWHP69X',
  );
}
